// packages/navbar-react/src/NavBar.tsx
import type { FC } from "react";

interface NavBarProps {
	title?: string;
}

export const NavBar: FC<NavBarProps> = ({ title = "Eltrue" }) => {
	return (
		<nav
			style={{
				backgroundColor: "#333",
				padding: "1rem",
				color: "white",
				display: "flex",
				justifyContent: "space-between",
				alignItems: "center",
			}}
		>
			<div style={{ fontSize: "1.5rem", fontWeight: "bold" }}>{title}</div>
			<div style={{ display: "flex", gap: "1rem" }}>
				<a href="/" style={{ color: "white", textDecoration: "none" }}>
					Home
				</a>
				<a href="/about" style={{ color: "white", textDecoration: "none" }}>
					About
				</a>
				<a href="/contact" style={{ color: "white", textDecoration: "none" }}>
					Contact
				</a>
			</div>
		</nav>
	);
};

// packages/navbar-webcomponent/src/NavBar.ts
export class NavBar extends HTMLElement {
	private navbarTitle: string;
	private shadow: ShadowRoot;

	constructor() {
		super();
		this.navbarTitle = this.getAttribute("title") || "Eltrue";
		this.shadow = this.attachShadow({ mode: "open" });
	}

	connectedCallback() {
		this.render();
	}

	static get observedAttributes() {
		return ["title"];
	}

	attributeChangedCallback(name: string, oldValue: string, newValue: string) {
		if (name === "title" && oldValue !== newValue) {
			this.navbarTitle = newValue;
			this.render();
		}
	}

	private render() {
		this.shadow.innerHTML = `
      <style>
        :host {
          display: block;
        }
        nav {
          background-color: #333;
          padding: 1rem;
          color: white;
          display: flex;
          justify-content: space-between;
          align-items: center;
        }
        .title {
          font-size: 1.5rem;
          font-weight: bold;
        }
        .links {
          display: flex;
          gap: 1rem;
        }
        a {
          color: white;
          text-decoration: none;
        }
      </style>
      <nav>
        <div class="title">${this.navbarTitle}</div>
        <div class="links">
          <a href="/">Home</a>
          <a href="/about">About</a>
          <a href="/contact">Contact</a>
        </div>
      </nav>
    `;
	}
}

customElements.define("eltrue-navbar", NavBar);
